### ISSUE TITLE
你好，我想问下这个最终的BELU值能达到多少

### ISSUE THREAD

**Issue by zhhao1** [macg0406/nmt_en2zh#1]

**Comment by zhhao1** [comment]
另外就是这个中文和英文的词表，在vocabulary文件夹里的那两个文件是怎么分词的呀

**Comment by macg0406** [comment]
我没有计算BELU值，训练中会输出测试集上的accuracy,用的是下一个词的top1准确率，最终在64%左右。

**Comment by macg0406** [comment]
> 另外就是这个中文和英文的词表，在vocabulary文件夹里的那两个文件是怎么分词的呀

词表和分词方法都是用的BERT的，提交的时候漏了一个文件，你可以下载一下放到vocabulary文件夹里，文件位置在 
https://github.com/google-research/bert/blob/master/tokenization.py  , 有一个import 路径需要改一下。

**Comment by zhhao1** [comment]
好的，谢谢。
